name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.66.2
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  intl: ^0.18.0
  connectivity_plus: ^5.0.2
  mockito: ^5.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - .env
    - env
